### ISSUE TITLE
Unit testing should be done for more classes

### ISSUE THREAD

**Issue by Molnarmala** [BME-MIT-IET/Mind1-iet-2018#10]
More classes should be tested. Obviously unit out goal is to test meaningful functions/classes. 

I think we cancover more if we go fore multiple classes withthe testing. (But considering the size of the project this is alreadí a good overall coverage)
![image](https://user-images.githubusercontent.com/26526210/40279191-53c776a8-5c3e-11e8-9e0f-27a19df4b449.png)

**Comment by KonradSuli** [comment]
Added unit tests for 3 different filter classes. RDFIsUriFilter, RDFIsLiteralFilter (they are kinda the same), and a third one for RDFBooleanAndFilter, which uses mocked objects, to track the behaviour. Can I get a coverage on them, just to make me feel good?

**Comment by Molnarmala** [comment]
The numbers are up, and the tests are done
![image](https://user-images.githubusercontent.com/26526210/40282474-2be653c0-5c70-11e8-944d-1feaeed2b640.png)
