### ISSUE TITLE
Unit Testing the RDFPattern class

### ISSUE THREAD

**Issue by Molnarmala** [BME-MIT-IET/Mind1-iet-2018#11]
A pretty simple class to testing, It should be done.

**Comment by FTim** [comment]
Wrote some tests. Looking for coverage results to add some more tests.

**Comment by Molnarmala** [comment]
Well the coverage is qute good (it doesn't include any other tests, only your tests for this class)
![image](https://user-images.githubusercontent.com/26526210/40280889-f3fe2a98-5c59-11e8-847e-bc5acee1278e.png)

**Comment by FTim** [comment]
Added some more tests for better coverage.

**Comment by Molnarmala** [comment]
Here is your result:
![image](https://user-images.githubusercontent.com/26526210/40281165-03d02332-5c5e-11e8-8355-06a9be38670f.png)
With this I think this class is finished.

Great job !
