### ISSUE TITLE
Writing example code.

### ISSUE THREAD

**Issue by KonradSuli** [BME-MIT-IET/Mind1-iet-2018#2]
Example codes should be written to test the basic functions of the libary.

**Comment by Molnarmala** [comment]
Aggreed! I nust assigned you for the task.
 Ask for help if you need some!

**Comment by KonradSuli** [comment]
Does this needs to be uploaded on a seperate branch, or is it okay if it stays local?

**Comment by Molnarmala** [comment]
We should make is go online. 
I just added a new Branch with a project suitable for the example code. Hope it helps!

**Comment by KonradSuli** [comment]
The very first bit of example code is up. Any suggestions to what we can do as examples?

**Comment by Molnarmala** [comment]
The code works well for me. I think it'll do fine as an example. Yes I know how few it seems compared to the code base, but it shows the basic cuse of the API. 
I think it passes.
The documentation should mention things the API provides but wasn't seen in the exampl code (eg. serialization support for different datatypes)

**Comment by KonradSuli** [comment]
Written a wiki page for the code, and where should it be documented? Is it relevant for me now?

**Comment by Molnarmala** [comment]
The wiki is good for documentation, and it seems fine.
