### ISSUE TITLE
We should set up a Continous Integration Server 

### ISSUE THREAD

**Issue by Molnarmala** [BME-MIT-IET/Mind1-iet-2018#3]
Continous Integration can be key to find out if something goes wrong. I suggest Travis as the CI tool of choice.

**Comment by FTim** [comment]
Added this repository to Travis. Also added a .travis.yml file with the following:
language: csharp
solution: RDFSharp.sln

Build not successful.

**Comment by Molnarmala** [comment]
It seems something is off with the build. But locally it builds just fine. (Using VS 2017)

Wait we should try something alongside this:
https://stackoverflow.com/questions/16751772/how-do-i-use-travis-ci-with-c-sharp-or-f/27413136

**Comment by Molnarmala** [comment]
It seems the mono vesion 3.12.0 does the job. (The rest aren't working, but at least this does work fine)

**Comment by FTim** [comment]
New wiki page added about CI server.
