### ISSUE TITLE
Fixing AddItem and RemoveItem coverage 

### ISSUE THREAD

**Issue by Molnarmala** [BME-MIT-IET/Mind1-iet-2018#9]
We should write tests for AddItem and RemoveItem functions in the RDFContainer class. In these test container instances should have a type other than ALT (eg: BAG).

The tests are mostly similar to the test we ran with ALT type containers. 

Two exceptions are the act of adding duplicate items to the container (ALT only supports one copy, other types like BAG supports multiple), and removing from the container if the item is present multiple times.

**Comment by jaklia** [comment]
Added tests for AddItem and RemoveItem functions for BAG and SEQ type containers

**Comment by Molnarmala** [comment]
Tests are in and the coveragewent up as expected:
![image](https://user-images.githubusercontent.com/26526210/40282481-5c4a8a04-5c70-11e8-91e8-658d36e6da3d.png)
